#ifndef __REVISION_SQL_H__
#define __REVISION_SQL_H__
#define REVISION_DB_CHARACTERS "required_s1699_xxxxx_01_characters_characters"
#define REVISION_DB_MANGOS "required_s1700_xxxxx_01_mangos_areatrigger_teleport"
#define REVISION_DB_REALMD "required_s1699_xxxxx_01_realmd_account_friends"
#endif // __REVISION_SQL_H__
